python main.py  --arch chinese_hubert_large \
                --name demo \
                --feature_dim 128 \
                --cov_dim 128 \
                --input_dim 39 \
                --seed 0 \
                --gamma 0.001 \
                --root_dir ./data \
                --train_blendshape_path ./data/wavs/org/train_37_original.pkl \
                --val_blendshape_path ./data/wavs/org/val_1_37_original.pkl \
                --num_workers 8 \
                --gpu 0 \
                --test_mode True \
